apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: default
data:
  mysql.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    bind_address=0.0.0.0
    symbolic-links=0
    pid-file=/var/run/mysqld/mysqld.pid

    [client]
    socket=/var/run/mysqld/mysqld.sock
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/

